import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background_primary h-full w-screen">
      <body className="min-h-screen text-lg text-white bg-tree relative">
        <div className="bg-gradient-overlay"></div>
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
