import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"

import { cn } from "~/lib/utils"
import { SideSheet } from "~/components/SideSheet"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background_primary h-full w-screen">
      <body className={cn(
        "min-h-screen font-sans antialiased text-lg bg-tree relative",
        fontSans.variable
      )}>
        <div className="bg-gradient-overlay">
          <div className="relative z-10 max-w-2xl mx-auto">
            <SideSheet />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
